version: '3.3'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro

  odoo:
    image: lykienminh/odoo-werp
    command: start
    restart: always
    ports:
      - 8069:8069
    links:
      - postgres:db
    volumes:
      - ./volumes/odoo/filestore:/opt/odoo/data/filestore
      - ./volumes/odoo/sessions:/opt/odoo/data/sessions
    environment:
      - TARGET_UID=0
      - ODOO_DB_HOST=db
      - ODOO_DB_PORT=5432
      - ODOO_DB_USER=odoo
      - ODOO_DB_PASSWORD=odoo
      - ODOO_DB_NAME=odoo-werp

# version: '3.1'
# services:
#   web:
#     image: werp
#     command: start
#     command: python3 odoo/odoo-bin -d odoo-werp --db_host db --db_user odoo --db_password odoo --db_port 8432
#     depends_on:
#       - mydb
#     ports:
#       - "8069:8069"
#     environment:
#     - HOST=mydb
#     - USER=odoo
#     - ODOO_ADMIN_PASSWD=admin
#     - PASSWORD=odoo
#     - HOST=db
#     - USER=odoo
#     - PORT=5432
#     - PASSWORD=odoo
#   mydb:
#     image: postgres:13
#     command: -p 8432
#     environment:
#       - POSTGRES_HOST_AUTH_METHOD=trust
#       - POSTGRES_DB=postgres
#       - POSTGRES_USER=odoo
#       - POSTGRES_PASSWORD=odoo
